### ISSUE TITLE
Build error Html5

### ISSUE THREAD

**Issue by zeonagames** [ShadowMario/NewVeryCoolPsychic#4]
### Describe your problem here.

I am getting error

source/PlayState.hx:1345: characters 8-16 : FlxVideo has no field disabled
source/PlayState.hx:1361: characters 25-33 : FlxVideo has no field disabled
source/PlayState.hx:1362: characters 25-34 : FlxVideo has no field vlcBitmap
source/PlayState.hx:1363: characters 25-34 : FlxVideo has no field vlcBitmap

### Are you modding a build from source or with Lua?

Source

### What is your build target?

HTML5/Browser

### Did you edit anything in this build? If so, mention or summarize your changes.

PlayState.hx

**Comment by ShadowMario** [comment]
kys
